name: Update Checksums

on:
  push:
  workflow_dispatch:

jobs:
  update-checksums:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: update checksums
        run: node update-checksums.js
      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "::set-output name=msg::$(git log -1 --pretty=%s)"
      - name: push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update checksums"