name: Update Checksums

on:
  push:
  workflow_dispatch:

jobs:
  update-checksums:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: update checksums
        run: node update-checksums.js
      - name: push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions